# Name: dog-tor
# Read a course name then print and average student grades.

# Set the file name and variables
$File = (Get-Content student_data.dat)
$Line = $null
[int]$LineCount = $null

# Preset values
[double]$Ass1 = $null
[double]$Ass2 = $null
[double]$Ass3 = $null
[double]$Ass4 = $null
[double]$MidTerm = $null
[double]$Final = $null
[double]$AvgAss1 = $null
[double]$AvgAss2 = $null
[double]$AvgAss3 = $null
[double]$AvgAss4 = $null
[double]$AvgMidTerm = $null
[double]$AvgFinal = $null
[double]$AvgGrade = $null

# Prompt for the course name
$CourseName = Read-Host "Enter Course Name"
Write-Output "`n`t`t`t`t`t`t`t`t`t`t`t`t`t`t$CourseName - Grades Report"
Write-Output "Full Name`t`t`tAssignment-1`tAssignment-2`tAssignment-3`tAssignment-4`tMid Term Exam`t`tFinal Exam`t`tGrade`tLetter Grade"
Write-Output "---------`t`t`t------------`t------------`t------------`t------------`t-------------`t`t----------`t`t-----`t------------"

# Assign and print the requried values for every line in the file
foreach ($Line in $File) {

    #Split fields into values
    $Line = $Line -split (",")
    $Name = $Line[0]
    $Ass1 = $Line[1]
    $Ass2 = $Line[2]
    $Ass3 = $Line[3]
    $Ass4 = $Line[4]
    $MidTerm = $Line[5]
    $Final = $Line[6]

    # Perform grade calculation
    $Grade = ($Ass1*.05) + ($Ass2*.05) + ($Ass3*.1) + ($Ass4*.1) + ($MidTerm*.3) + ($Final*.4)

    # Conditional statement to determine the letter grades
    switch ($Grade) {
        { $Grade -ge 89.5} {$LetterGrade = "A"; break}
        { $Grade -le 89.4 -and $Grade -ge 79.5 } {$LetterGrade = "B"; break}
        { $Grade -le 79.4 -and $Grade -ge 69.5 } {$LetterGrade = "C"; break}
        { $Grade -le 69.4 -and $Grade -ge 59.5 } {$LetterGrade = "D"; break}
        { $Grade -le 59.4 } {$LetterGrade = "F"; break}
        default {"The letter grade could not be determined."}
        }

    # Print each series of grades for each student
    "{0,-23} {1,-15:n2} {2,-15:n2} {3,-15:n2} {4,-15:n2} {5,-18:n2} {6,-12:n2} {7,-13:n2} {8,-15}" -f $name,$Ass1,$Ass2,$Ass3,$Ass4,$MidTerm,$Final,$Grade,$LetterGrade

    # Calculate the averages P1
    $AvgAss1+=$Ass1
    $AvgAss2+=$Ass2
    $AvgAss3+=$Ass3
    $AvgAss4+=$Ass4
    $AvgMidTerm+=$MidTerm
    $AvgFinal+=$Final
    $AvgGrade+=$Grade

    # Count the iterations to calculate the average P2
    $LineCount++

    }

# Calculate the averages P3
$AvgAss1= $AvgAss1/$LineCount
$AvgAss2=$AvgAss2/$LineCount
$AvgAss3=$AvgAss3/$LineCount
$AvgAss4=$AvgAss4/$LineCount
$AvgMidTerm=$AvgMidTerm/$LineCount
$AvgFinal=$AvgFinal/$LineCount
$AvgGrade=$AvgGrade/$LineCount

Write-Output "---------------------------------------------------------------------------------------------------------------------------------------"
"{0,-23} {1,-15:n2} {2,-15:n2} {3,-15:n2} {4,-15:n2} {5,-18:n2} {6,-12:n2} {7,-13:n2}" -f "Class Averages:",$AvgAss1,$AvgAss2,$AvgAss3,$AvgAss4,$AvgMidTerm,$AvgFinal,$AvgGrade
Write-Output "---------------------------------------------------------------------------------------------------------------------------------------"
Write-Output "`nReport Generated By: dog-tor @$(Get-Date -Format "dddd MMMM dd,yyyy hh:mm:ss")"

